# Generated by Django 2.1.8 on 2019-05-20 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contnet',
            new_name='content',
        ),
    ]
