# Generated by Django 2.1.8 on 2019-05-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0002_auto_20190529_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(through='manytomany.Reservation', to='manytomany.Doctor'),
        ),
    ]
